server:
  port: 8080
spring:
#  thymeleaf配置
  thymeleaf:
#    关闭缓存
    cache: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hello?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
#      连接池名
      pool-name: DateHikariCP
#      最小空闲连接数
      minimum-idle: 6
#      空闲连接存活最大时间, 默认600000ms(10分钟)
      idle-timeout: 180000
#      最大空闲连接数
      maximum-pool-size: 10
#      从连接池返回的连接自动提交
      auto-commit: true
#      连接存活最大时间, 0表示永久存活, 默认1800000(30分钟)
      max-lifetime: 180000
#      连接超时时间
      connection-timeout: 30000
#      测试连接是否可用的查询语句
      connection-test-query: SELECT 1

mybatis-plus:
#  配置Mapper.xml配置文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  配置mybatis数据返回类型别名
  type-aliases-package: com.example.pojo

# Mybatis SQL打印(方法接口所在的包)
logging:
  level:
    com.example.mapper: debug
